info:
    desc: client222
server:
  port: 8082
management:
  context-path: "/manage"
  security:
    enabled: true
spring.application.name: CLIENT-2
spring:
  boot:
    admin:
      url: http://localhost:8080 #注册服务器的地址
      username: admin #注册的目标服务器端的用户名密码
      password: admin
      client:  # 告诉服务端访问我接口的用户名以及密码
        metadata:
           user.name: "${security.user.name}"
           user.password: "${security.user.password}"
security:
  user:
    name: client2
    password: client2client2client2
  basic:
    enabled: true # 设置验证模式为basic admin服务器请求actuator时会使用客户端的发送的用户名密码
  ignored:
      - /api/**
      - /index
      - /
logging:
  level: info



